services:
  fusion-revive:
    container_name: fusion-revive
    image: ghcr.io/slemens/fusion-revive
    volumes:
      - /path/to/fusion-revive:/app/data
    network_mode: bridge
    ports:
      - 5050:5050
    environment:
      TZ: Europe/Berlin
      HASS_URL: http://192.168.1.X:8123
    restart: always
